### PR TITLE
Remove incorrectly set compileOpions

### PR DESCRIPTION
**Pull request by rschiu**

### CODE REVIEW

**Comment by proppy** [comment]
IIRC that was done to make sure java7 is selected on a host os that also have java8.

Should we move this instead under the android block?

**Comment by proppy** [comment]
`app:dexArm7Debug` was failing with java8, is that fixed now?

**Comment by rschiu** [comment]
It should default to java 6.  So it would still work for java 8.  I'll double check to make sure.  We shouldn't set compileOptions for the users.

**Comment by proppy** [comment]
>  We shouldn't set compileOptions for the users.

Yes, this was more of a temporary workaround, because multiple reports came up with this issue and we wanted the sample to work out of the box.

See #52 #34 #40 #60.

**Comment by rschiu** [comment]
I tested it works with hello-jni arm7Debug.  Which project do you mean for app:dexArm7Debug?

**Comment by proppy** [comment]
@rschiu that was the step failing when java8 is installed, see #52 #34

**Comment by rschiu** [comment]
Ok, that is fixed now.  Please accept the pull request.  Thanks

**Comment by proppy** [comment]
@rschiu, sure can you comment here on the commit/bug that fixed it? thanks.

**Comment by proppy** [comment]
Note that #144 was also fixed the bad scoping of the `compileOptions`. I'll drop this change from it.

**Pull request merged**
