### PR TITLE
Update Teapot sample to use C++11's std::isnan()

### PR DESCRIPTION
**Pull request by ggfan**
Compiler is tighting supportability for earlier versions
to comply with standard

### CODE REVIEW

**Comment by ggfan** [comment]
@bbilodeau @danalbert please kindly take a look.  thanks!

**Comment by bbilodeau** [comment]
LGTM

**Comment by DanAlbert** [comment]
There was a bug identified here and this commit is unnecessary.

**Comment by ggfan** [comment]
thanks.  I will put it back next time

**Pull request merged**
