### PR TITLE
bump gradle android plugin to 0.4.0

### PR DESCRIPTION
**Pull request by proppy**
We should merge this once it's not alpha anymore.

### CODE REVIEW

**Comment by ggfan** [comment]
LGTM

**Comment by proppy** [comment]
@ggfan not LGTM, the build is failing :)

**Comment by proppy** [comment]
Changelog from @rschiu
Fixed issue with using jni code in experimental library plugin.
Allow platform version to be set separately from compileSdkVersion in experimental plugin.
Allow ABI specific configurations in a variant that contains multiple ABI.
An preview version of an standalone plugin for compiling just native code is now available.  It can be use to build application with Gradle, but support in Android Studio is not yet implemented.
Added support for dependencies on NDK plugin and shared object/static library files.

**Comment by proppy** [comment]
@rschiu I bumped the dependencies to alpha5, let's see if the CI builds pass now.

**Comment by rschiu** [comment]
LGTM

**Pull request merged**
