### PR TITLE
MoreTeapot: fix android lint warning

### PR DESCRIPTION
**Pull request by proppy**
/cc @hak @ggfan @claywilkinson

This remove lint warning from MoreTeaport sample.
- bump `minsdk` from `11` to `19` since the code has some 19 only API calls.
- update icon to default android studio mipmap
- switch to RTL attributes for text placement
- move text to resources

### CODE REVIEW

**Comment by claywilkinson** [comment]
LGTM

**Comment by hak** [comment]
For setSystemUiVisibility() (API-19), the code is checking API level and falling back to other pass.
So if this is the only reason to bump up the API level, we don't have to do that.

**Comment by proppy** [comment]
@hak PTAL

**Comment by hak** [comment]
LGTM, too.

**Pull request merged**
