### PR TITLE
Update SDK Version to 25

### PR DESCRIPTION
**Pull request by adithya321**

### CODE REVIEW

**Comment by ggfan** [comment]
thank you for the Pull Request! Like to hold for this update to 2.3 - Beta3:  I think significant amount of people is still on the stable release, might be good to hold this update for a couple of more weeks.

**Comment by ggfan** [comment]
the formal 2.3 is released: 
https://developer.android.com/studio/index.html

Earlier personally I experienced something strange with preview version, now we could update samples to formal 2.3 release.  May you kindly update it with the formal version and do some sanity check?  then we could merge the PR

thanks

**Comment by adithya321** [comment]
Updated to 2.3.0.

**Comment by ggfan** [comment]
LGTM

**Pull request merged**
