### PR TITLE
camera/**/camera_manager.cpp: iterate entry properly

### PR DESCRIPTION
**Pull request by justinjoy**
Looping all entry count is too long and the extracted values might not be expected.
` entry.count` has the total number of entry.

### CODE REVIEW

**Comment by ggfan** [comment]
thanks for the PR: that means the "entry" means the count of the elements of int32_t type, not the total configuration entries. let me check on android source code tmr and then merge.

**Comment by justinjoy** [comment]
Please, refer to my question and Alex's reply. https://groups.google.com/d/msg/android-ndk/piFVEtmpshc/GasENGx6BQAJ

**Comment by justinjoy** [comment]
I think I signed it as a member of the company group. What's wrong with CLA bot?

**Comment by ggfan** [comment]
yeah, it is bug.  in  PrintStreamConfigurations() / camera_utils.cpp having the same thing:
void PrintStreamConfigurations(ACameraMetadata_const_entry& val) {
#define MODE_LABLE "ModeInfo:"
  const char* tagName = GetTagStr(static_cast<acamera_metadata_tag_t>(val.tag));
  ASSERT(!(val.count & 0x3), "STREAM_CONFIGURATION (%d) should multiple of 4",
         val.count);
  ASSERT(val.type == ACAMERA_TYPE_INT32,
         "STREAM_CONFIGURATION TYPE(%d) is not ACAMERA_TYPE_INT32(1)",
         val.type);
  LOGI("%s -- %s:", tagName, MODE_LABLE);
  for (uint32_t i = 0; i < val.count; i += 4) {
    LOGI("%s: %08d x %08d  %s", GetFormatStr(val.data.i32[i]),
         val.data.i32[i + 1], val.data.i32[i + 2],
         val.data.i32[i + 3] ? "INPUT" : "OUTPUT");
  }
#undef MODE_LABLE
}
I will merge it

**Pull request merged**
